package validation

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// --- Rule 18: Each construct must have template files ---

func checkRule18(relDir, constructDir, constructName string, _ AuditOptions) []Violation {
	// Check for entity schema files.
	entries, err := os.ReadDir(constructDir)
	if err != nil {
		return nil
	}
	hasEntitySchema := false
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".yaml") && e.Name() != "api.yml" && !strings.Contains(e.Name(), "_template") {
			hasEntitySchema = true
			break
		}
	}
	if !hasEntitySchema {
		return nil
	}

	templatesDir := filepath.Join(constructDir, "templates")
	var out []Violation

	if info, err := os.Stat(templatesDir); err != nil || !info.IsDir() {
		out = append(out, Violation{File: relDir, Message: fmt.Sprintf(`Construct %q has no templates/ subdirectory.`, constructName), Severity: SeverityBlocking, RuleNumber: 18})
		return out
	}

	templateEntries, err := os.ReadDir(templatesDir)
	if err != nil {
		return nil
	}
	hasTemplate := false
	for _, e := range templateEntries {
		if strings.Contains(e.Name(), "_template") {
			hasTemplate = true
			break
		}
	}
	if !hasTemplate {
		out = append(out, Violation{File: relDir, Message: fmt.Sprintf(`Construct %q has templates/ directory but no template files.`, constructName), Severity: SeverityBlocking, RuleNumber: 18})
	}

	// Check for misplaced templates at root.
	for _, e := range entries {
		if strings.Contains(e.Name(), "_template") {
			out = append(out, Violation{File: relDir,
				Message: fmt.Sprintf(`Construct %q has template file(s) at root level: %s. Move to templates/ subdirectory.`, constructName, e.Name()),
				Severity: SeverityBlocking, RuleNumber: 18})
		}
	}

	return out
}

// --- Rule 22: Helper files must have "not autogenerated" marker ---

func checkRule22(relPath, absPath string, _ AuditOptions) []Violation {
	data, err := os.ReadFile(absPath)
	if err != nil {
		return nil
	}
	lines := strings.SplitN(string(data), "\n", 6)
	header := strings.ToLower(strings.Join(lines, "\n"))
	if !strings.Contains(header, "not autogenerated") && !strings.Contains(header, "not auto-generated") {
		return []Violation{{
			File:       relPath,
			Message:    `Manual helper file is missing "not autogenerated" marker in its header. Add // This is not autogenerated. in the first few lines.`,
			Severity:   SeverityBlocking,
			RuleNumber: 22,
		}}
	}
	return nil
}

// --- Rule 34: Template file values must match schema property types ---

func checkRule34(relDir, constructDir string, _ AuditOptions) []Violation {
	templatesDir := filepath.Join(constructDir, "templates")
	if _, err := os.Stat(templatesDir); err != nil {
		return nil
	}

	entitySchemas, err := os.ReadDir(constructDir)
	if err != nil {
		return nil
	}

	var out []Violation
	for _, e := range entitySchemas {
		if !strings.HasSuffix(e.Name(), ".yaml") || e.Name() == "api.yml" || strings.Contains(e.Name(), "_template") {
			continue
		}
		schemaPath := filepath.Join(constructDir, e.Name())
		schema, err := loadEntitySchema(schemaPath)
		if err != nil || schema == nil || schema.Properties == nil {
			continue
		}

		baseName := strings.TrimSuffix(e.Name(), ".yaml")
		tmplEntries, err := os.ReadDir(templatesDir)
		if err != nil {
			continue
		}
		for _, tmplEntry := range tmplEntries {
			if !strings.Contains(tmplEntry.Name(), baseName+"_template") {
				continue
			}
			tmplPath := filepath.Join(templatesDir, tmplEntry.Name())
			tmplData, err := os.ReadFile(tmplPath)
			if err != nil {
				continue
			}
			var tmpl map[string]any
			if strings.HasSuffix(tmplEntry.Name(), ".json") {
				if err := json.Unmarshal(tmplData, &tmpl); err != nil {
					continue
				}
			} else {
				if err := yaml.Unmarshal(tmplData, &tmpl); err != nil {
					continue
				}
			}
			if tmpl == nil {
				continue
			}

			relTmpl := filepath.ToSlash(filepath.Join(relDir, "templates", tmplEntry.Name()))
			for key, val := range tmpl {
				prop, ok := schema.Properties[key]
				if !ok || prop == nil || prop.Type == "" {
					continue
				}
				if val == nil {
					continue
				}
				_, isArray := val.([]any)
				jsType := "object"
				if isArray {
					jsType = "array"
				} else {
					switch val.(type) {
					case string:
						jsType = "string"
					case float64, int:
						jsType = "number"
					case bool:
						jsType = "boolean"
					}
				}

				if prop.Type == "string" && jsType == "object" {
					out = append(out, Violation{File: relTmpl,
						Message:  fmt.Sprintf(`Template property %q is an object but schema declares type: string. Use an empty string "" as the default.`, key),
						Severity: SeverityBlocking, RuleNumber: 34})
				}
				if prop.Type == "array" && jsType == "object" && !isArray {
					out = append(out, Violation{File: relTmpl,
						Message:  fmt.Sprintf(`Template property %q is an object {} but schema declares type: array. Use an empty array [] as the default.`, key),
						Severity: SeverityBlocking, RuleNumber: 34})
				}
				if (prop.Type == "integer" || prop.Type == "number") && jsType == "string" {
					out = append(out, Violation{File: relTmpl,
						Message:  fmt.Sprintf(`Template property %q is a string but schema declares type: %s. Use 0 as the default.`, key, prop.Type),
						Severity: SeverityBlocking, RuleNumber: 34})
				}
			}
		}
	}
	return out
}
