// Package schedule provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package schedule

import (
	externalRef0 "github.com/meshery/schemas/models/v1alpha1/core"
)

// Schedule A schedule defines a recurring cron-based trigger for performance tests or other automated tasks.
type Schedule struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Id *externalRef0.Uuid `db:"id" json:"id,omitempty" yaml:"id,omitempty"`

	// Name Human-readable name for the schedule.
	Name string `db:"name" json:"name" yaml:"name"`

	// UserId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	UserId externalRef0.Uuid `db:"user_id" json:"user_id" yaml:"user_id"`

	// CronExpression Cron expression defining the schedule's recurrence (e.g. "0 0 * * *" for daily at midnight).
	CronExpression string `db:"cron_expression" json:"cron_expression" yaml:"cron_expression"`

	// CreatedAt Timestamp when the resource was created.
	CreatedAt externalRef0.CreatedAt `db:"created_at" json:"created_at,omitempty" yaml:"created_at,omitempty"`

	// UpdatedAt Timestamp when the resource was updated.
	UpdatedAt externalRef0.UpdatedAt `db:"updated_at" json:"updated_at,omitempty" yaml:"updated_at,omitempty"`
}

// SchedulePage A paginated list of schedules.
type SchedulePage struct {
	// Page Current page number (zero-based).
	Page int `json:"page" yaml:"page"`

	// PageSize Number of schedules per page.
	PageSize int `json:"page_size" yaml:"page_size"`

	// TotalCount Total number of schedules across all pages.
	TotalCount int        `json:"total_count" yaml:"total_count"`
	Schedules  []Schedule `json:"schedules" yaml:"schedules"`
}

// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type Id = externalRef0.Uuid

// ExternalRef0Order defines model for order.
type ExternalRef0Order = string

// ExternalRef0Page defines model for page.
type ExternalRef0Page = string

// ExternalRef0Pagesize defines model for pagesize.
type ExternalRef0Pagesize = string

// ExternalRef0Search defines model for search.
type ExternalRef0Search = string
